version: '3.6'
services:
  demo-quartz:
    image: aironman/demo-quartz:0.0.1-SNAPSHOT
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
          condition: on-failure
    links:
      - kafka
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock